POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "adminz",
  "firstName": "gjdrgdf",
  "lastName": "last e3434rfe3434ffrrfrname 1",
  "email": "rrferf@gmail.com",
  "password": "adminxc",
  "phone": "+375(29)338-73-30"
}

###
POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "name": "adminz",
  "password": "adminxc"

}

###

DELETE http://localhost:8080/user/adminz
Content-Type: application/json


###
POST http://localhost:8080/pet
Content-Type: application/json
//Key: 46ad16fc-ff30-418e-bc82-4538fe72d8aa

{
  "category": {
    "name": "sdfdf"
  },
  "name": "Odfdf",
  "tags": [
    {
      "name": "string1"
    },
    {
      "name": "string2"
    }
  ],
  "status": "SOLD"
}

###
GET http://localhost:8080/pet/all
Content-Type: application/json
###
DELETE http://localhost:8080/pet/1
Content-Type: application/json
###

###
GET http://localhost:8080/user/admin
Content-Type: application/json

###
POST http://localhost:8080/store/order
Key: 72f3536c-f53d-42fc-936e-a4d89902139d

{
  "id": 1,
  "petId": 1,
  "quantity": 2,
  "shipDate": "2021-03-02T05:57:09.472Z",
  "status": "PLACED",
  "complete": true
}
###
GET http://localhost:8080/store/all
Key:72f3536c-f53d-42fc-936e-a4d89902139d
###
GET http://localhost:8080/store/order/2
Content-Type: application/json