POST http://localhost:8080/user
Content-Type: application/json

{
  "name": "adminqe",
  "firstName": "gjdrgdf",
  "lastName": "last e3434rfe3434ffrrfrname 1",
  "email": "rrferf@gmail.com",
  "password": "admin",
  "phone": "+375(29)338-73-30"
}

###
POST http://localhost:8080/user/auth
Content-Type: application/json

{
  "name": "admin",
  "password": "admin"

}

###
GET http://localhost:8080/user/all
X-Key:ef2e5331-83a8-4008-9d7c-c28c845142e9
###
DELETE http://localhost:8080/user/admin
X-Key:4c778250-f53c-43b1-917a-8b1e6fafdcb3


###
POST http://localhost:8080/pet
Content-Type: application/json
//Key: 46ad16fc-ff30-418e-bc82-4538fe72d8aa

{
  "category": {
    "name": "12123"
  },
  "name": "Odfdf",
  "tags": [
    {
      "name": "string3"
    },
    {
      "name": "string2"
    }
  ],
  "status": "SOLD"
}

###
GET http://localhost:8080/pet/all
Content-Type: application/json
###
DELETE http://localhost:8080/pet/1
Content-Type: application/json
###

###
GET http://localhost:8080/user/admin
Content-Type: application/json

###
POST http://localhost:8080/store/order
Key: 72f3536c-f53d-42fc-936e-a4d89902139d

{
  "id": 1,
  "petId": 1,
  "quantity": 2,
  "shipDate": "2021-03-02T05:57:09.472Z",
  "status": "PLACED",
  "complete": true
}
###
GET http://localhost:8080/store/all
Key:72f3536c-f53d-42fc-936e-a4d89902139d
###
GET http://localhost:8080/store/order/2
Content-Type: application/json